### ISSUE TITLE
Discussions about the mask implementation

### ISSUE THREAD

**Issue by youngboy52** [GANtastic3/MaskCycleGAN-VC#10]
Thank you for your code! I found a confusion: 
According to the original paper, the mask is used in the source mel-spectrongram instead of target mel-spectrongram, while both Mel-spectrongrams use mask in your scripts. Why does target side also uses mask? Looking forward to your reply!

**Comment by hikaruhotta** [comment]
Hi @youngboy52, do you mind linking a specific line that does this?

**Comment by youngboy52** [comment]
> Hi @youngboy52, do you mind linking a specific line that does this?

Thank you for your reply. I found the masks are used in both source and target Mel-spectrongram, please refer to https://github.com/GANtastic3/MaskCycleGAN-VC/blob/d1d66b575669b03765c0d8d8ffd33d4fbacc0936/dataset/vc_dataset.py#L54 and https://github.com/GANtastic3/MaskCycleGAN-VC/blob/d1d66b575669b03765c0d8d8ffd33d4fbacc0936/dataset/vc_dataset.py#L67. But in MaskCycleGAN paper, the mask only implements on source Mel-spectrongram as follows:
![image](https://user-images.githubusercontent.com/15629424/118913366-e4fed300-b95b-11eb-9058-23a88e897c8b.png)
I doubt that the mask in target Mel-spectrongram will loss some speaker information, and make a bad influence on the VC performance.

**Comment by szalouk** [comment]
Hi @youngboy52, 

We added a mask for the target Mel Spectrogram to have symmetry in our CycleGAN in both directions during training, so that both generators can effectively learn the time frequency structure of the Mel Spectrogram. Our implementation still follows the paper as it pertains to the section you pasted above. During training, when converting from A (source) to B (target), we apply mask_A to A and generate fake_B. When producing the reconstruction, i.e. rec_A, we apply a matrix of ones to fake_B, as suggested in the paper. We only apply mask_B to B when training the reverse generator (i.e. from B (target) to A (source)) in a symmetric way. Since the paper suggests that a matrix of ones should be passed in to the generator when generating rec_A, it suggests that the reverse generator BtoA should be trained to accept a mask in a similar way to the forward generator AtoB as we have done in our code. Otherwise, the reverse generator BtoA would not need an extra channel for a matrix of ones.

Hope that clarifies our choice behind our implementation decision.
